### Connect
POST http://localhost:8080/auth
Content-Type: application/json

{
  "pseudo": "test",
  "password": "test"
}

> {%
  client.global.set("test", response.body.token);
%}

### Create  one user
POST http://localhost:8080/users/test
Content-Type: application/json

{
  "pseudo": "test",
  "firstname": "testFirstname",
  "lastname": "testLastname",
  "password": "test"
}

### Read one user
GET http://localhost:8080/users/test

### Create  one user
PUT http://localhost:8080/users/test
Content-Type: application/json
Authorization: {{test}}

{
  "pseudo": "test",
  "firstname": "testFirstnameUpdated",
  "lastname": "testLastname",
  "password": "test"
}