### ReadAll
GET http://localhost:9001/produits

### CreateOne
POST http://localhost:9001/produits
Content-Type: application/json

{
  "name": "Produit4",
  "category": "Categorie2",
  "price": 30.0
}

### UpdateOne
PUT http://localhost:9001/produits/4
Content-Type: application/json

{
  "id": 4,
  "name": "Produit4",
  "category": "Categorie2",
  "price": 29.99
}

### DeleteOne
DELETE http://localhost:9001/produits/4
Content-Type: application/json

### DeleteAll
DELETE http://localhost:9001/produits
Content-Type: application/json