### Create one cartItem
POST http://localhost:9003/carts/users/NightHawk/products/1
Content-Type: application/json

{
  "productId": 1,
  "pseudo": "NightHawk"
}

### Create one cartItem
POST http://localhost:9003/carts/users/NightHawk/products/3
Content-Type: application/json

{
  "productId": 3,
  "pseudo": "NightHawk"
}

### Create one cartItem
POST http://localhost:9003/carts/users/GhostRider/products/1
Content-Type: application/json

{
  "productId": 1,
  "pseudo": "GhostRider"
}

### Create one cartItem
POST http://localhost:9003/carts/users/GhostRider/products/3
Content-Type: application/json

{
  "productId": 3,
  "pseudo": "GhostRider"
}

### Delete one cartItem
DELETE http://localhost:9003/carts/users/NightHawk/products/1
Content-Type: application/json

### Delete all cartItem
DELETE http://localhost:9003/carts/users/NightHawk
Content-Type: application/json

### Delete specific product from all cart
DELETE http://localhost:9003/carts/products/1
Content-Type: application/json

### Get user cart product
GET http://localhost:9003/carts/users/NightHawk

### Get user cart product
GET http://localhost:9003/carts/users/GhostRider