openapi: 3.0.3
info:
  title: Amazing Product Service
  description: Title
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
    description: Local server
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: Id du produit
        name:
          type: string
          description: Nom du produit
        category:
          type: string
          description: Categorie du produit
        price:
          type: number
          description: Prix du produit
      example:
        id: 1
        name: Produit1
        category: Categorie1
        price: 30
paths:
  /produits:
    get:
      summary: Get all products
      operationId: getAllProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

